version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: cabinet_postgress
    restart: always
    environment:
      POSTGRES_USER: cabinet
      POSTGRES_PASSWORD: cabinetpass
      POSTGRES_DB: cabinet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
